### PR TITLE
Small refactoring

### PR DESCRIPTION
**Pull request by Obolrom**
1. Added volatile flags for 2 boolean flag initializers
2. In UiRequestViewModel nullable job field was replaced with a coroutine scope
3. Fixed typo in a class name

### CODE REVIEW

**Comment by RadiationX** [comment]
Thanks for the PR.
Question - what problem does item 2 (observingNewScope) solve?

**Comment by Obolrom** [comment]
I had no problems with this particular place in the code, but launching and canceling a coroutine using a coroutine scope is more preferred and safe according to the creators of kotlin coroutines

**Comment by RadiationX** [comment]
Understood.  In this case, I propose to roll back these changes, because.  with job on idea of ​​problems should not be.

**Comment by Obolrom** [comment]
Made rollback. Now it should be fine

**Pull request merged**
